### PR TITLE
Create ResourceSpace database with Ansible

### PR DESCRIPTION
**Pull request by nvanderperren**
This PR solves #9

### CODE REVIEW

**Review by netsensei — COMMENTED** [review]
If possible, try to create a dedicated MySQL user for a database with a separate password (i.e. db: resourcespace, user: resourcespace, pass: R3sourc3Space!)

It's always good practice to be mindful about security. Even in a development environment on a local machine. When we move towards a live environment, we should store passwords in Ansible Vault (https://docs.ansible.com/ansible/latest/user_guide/vault.html) This creates encrypted files instead of storing passwords as plaintext in Ansible Roles.

**Review by Hobbesball — APPROVED** [review]
I have nothing to add to @netsensei's comments, thanks for this! It will make automatic setup of RS in the imagehub box a bunch easier <3

**Comment by nvanderperren** [comment]
I'll add the user first then!

**Review by netsensei — APPROVED** [review]
Looks good to me, let's merge this.

**Pull request merged**
